site_name: Workshop Estrutura do Zero
theme:
  name: material
  palette:
    primary: teal
  language: pt

repo_name: 'lucasftorres/workshop_estrutura_do_zero'
repo_url: 'https://github.com/lucasftorres/workshop_estrutura_do_zero'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python